import React from 'react'

const products = [
    {
      id: 1,
      name: "Apple iPhone 13 (128GB) - Blue",
      price: 493,
      imageUrl: "/images/Iphone 13(128gb) blue 1.jpg",
    },
    {
      id: 2,
      name: "Dell Latitude 7420 Laptop",
      price: 1118,
      imageUrl: "/images/Dell Latitude 7420.jpg",
    },
    {
      id: 3,
      name: "Apple iPhone 13 (128GB) - Green",
      price: 502,
      imageUrl: "/images/Iphone 13(128gb) Green 1.jpg",
    },
    {
      id: 4,
      name: "Apple AirPods Pro (2nd Generation)",
      price: 222,
      imageUrl: "/images/Apple Airpods 2nd Gen.jpg",
    },
    {
      id: 5,
      name: "Apple iPhone 13 (256GB) - Red",
      price: 742,
      imageUrl: "/images/Iphone 13(128gb) Red 1.jpg",
    },
    {
      id: 6,
      name: "Lenovo Tab M10 FHD 3rd Gen| 10.1 Inch (Storm Grey)",
      price: 94,
      imageUrl: "/images/Lenovo Tab P11.webp",
    },
    {
      id: 7,
      name: "Apple iPhone 13 (512GB) - Green",
      price: 786,
      imageUrl: "/images/Iphone 13(128gb) Green 1.jpg",
    },
    {
      id: 8,
      name: "Samsung Galaxy Buds2 Pro (Bora Purple)",
      price: 156,
      imageUrl: "/images/Samsung Galaxy Buds pro2.jpg",
    },
    {
      id: 9,
      name: "boAt BassHeads 122 Wired in Earphones (Gun Metal)",
      price: 3,
      imageUrl: "/images/Boat Bassheads 122.webp",
    },
    {
      id: 10,
      name: "Apple iPhone 14 (128GB) - Midnight",
      price: 568,
      imageUrl: "/images/Iphone 14(128gb) Midnight.jpg",
    },
    {
      id: 11,
      name: "Portronics Key7 Wireless Keyboard & Mouse Set",
      price: 8,
      imageUrl: "/images/Keyboard And Mouse.webp",
    },
    {
      id: 12,
      name: "Apple Iphone 14 Pro",
      price: 1147,
      imageUrl: "/images/Iphone 14 pro.jpg",
    },
    {
      id: 13,
      name: "Apple Iphone 14 Pro Max",
      price: 1213,
      imageUrl: "/images/Iphone 14 pro max.jpg",
    },
    {
      id: 14,
      name: "Apple 20W USB-C Power Adapter",
      price: 15,
      imageUrl: "/images/Apple 20W adaptor.jpg",
    },
    {
      id: 15,
      name: "Apple iPad Pro 11″ (4th Generation - Silver",
      price: 757,
      imageUrl: "/images/Apple ipad 11 pro.jpg",
    },
    {
      id: 16,
      name: "Apple Iphone 15 Pro",
      price: 1308,
      imageUrl: "/images/Iphone 15 Pro.jpg",
    },
    {
      id: 17,
      name: "USB C to Lightning Cable iPhone Fast Charger Cable",
      price: 6,
      imageUrl: "/images/Apple Charging Cable.jpg",
    },
    {
      id: 18,
      name: "Samsung Galaxy S24 5G AI Smartphone",
      price: 758,
      imageUrl: "/images/Samsung S24.webp",
    },
    {
      id: 19,
      name: "Sony Bravia 189 cm (75 inches) 4K Ultra TV KD-75X82L (Black)",
      price: 1395,
      imageUrl: "/images/Sony Bravia 189cm.jpg",
    },
    {
      id: 20,
      name: "Samsung Galaxy S24 Ultra 5G AI Smartphone",
      price: 1327,
      imageUrl: "/images/Samsung S24 Ultra.webp",
    },
    {
      id: 21,
      name: "Apple Watch SE (2nd Gen) [GPS 40 mm] ",
      price: 273,
      imageUrl: "/images/Apple Watch SE(2nd Gen).webp",
    },
    {
      id: 22,
      name: "Samsung Galaxy S23 FE",
      price: 521,
      imageUrl: "/images/Samsung S23 FE.webp",
    },
    {
      id: 23,
      name: "Logitech G F310 Wired Gamepad - Grey/Blue",
      price: 20,
      imageUrl: "/images/Logitech Wired Gamepad.webp",
    },
    {
      id: 24,
      name: "OnePlus Nord CE 3 Lite 5G",
      price: 189,
      imageUrl: "/images/OnePlus Nord CE 3 Lite 5G.webp",
    },
    {
      id: 25,
      name: "OnePlus 12",
      price: 616,
      imageUrl: "/images/OnePlus 12.jpg",
    },
    {
      id: 26,
      name: "Xiaomi 360 Home Security Wireless Camera",
      price: 37,
      imageUrl: "/images/Xiaomi 360 Home security wireless Camera.webp",
    },
    {
      id: 27,
      name: "OnePlus 11R 5G",
      price: 398,
      imageUrl: "/images/OnePlus 11R.webp"
    },
    {
      id: 28,
      name: "OnePlus Nord 2T 5G",
      price: 322,
      imageUrl: "/images/OnePlus Nord 2T.webp",
    },
    {
      id: 29,
      name: "OnePlus 11 5G",
      price: 587,
      imageUrl: "/images/OnePlus 11.jpg",
    },
    {
      id: 30,
      name: "IQOO NEO 9 Pro",
      price: 350,
      imageUrl: "/images/IQOO Neo 9 Pro.jpg",
    },
    {
      id: 31,
      name: "Redmi 12 5G",
      price: 127,
      imageUrl: "/images/Redmi 12.webp",
    },
    {
      id: 32,
      name: "Dell Inspiron 15 (5568/5567) 13 (5368/5378) 7368 42Whr 3Cell Battery",
      price: 24,
      imageUrl: "/images/Dell Inspiration 15.jpg",
    },
    {
      id: 33,
      name: "Sony Digital Vlog Camera ZV 1 - Black",
      price: 663,
      imageUrl: "/images/Sony Vlog Camera.jpg",
    },
    {
      id: 34,
      name: "Insta360 X3 Action Camera",
      price: 398,
      imageUrl: "/images/Insta360 Action Camera.jpg",
    },
    {
      id: 35,
      name: "Digitek (MCUV77) DSLR Camera Protection Lens",
      price: 4,
      imageUrl: "/images/Digitek Camera lens.jpg",
    },
    {
      id: 36,
      name: "Skullcandy Hesh ANC Bluetooth Wireless Over-Ear Headphones with Mic (Black)",
      price: 80,
      imageUrl: "/images/SkullCandy Headphones.jpg",
    },
    {
      id: 37,
      name: "Skullcandy Jib (S2DUY-L676) Wired In Ear Earphone with Mic (Black/Red)",
      price: 5,
      imageUrl: "/images/Skullcandy Wired Earphones.jpg",
    },
    {
      id: 38,
      name: "GIZMORE Portable Bluetooth Soundbar ",
      price: 37,
      imageUrl: "/images/Gizmore Soundbar.webp",
    },
    {
      id: 39,
      name: "Nokia G42 5G",
      price: 118,
      imageUrl: "/images/Nokia G42.webp",
    },
    {
      id: 40,
      name: "ZEBRONICS PIXAPLAY 18, Smart Vertical Projector",
      price: 189,
      imageUrl: "/images/Zebronics projector.webp",
    },
    {
      id: 41,
      name: "Dell Inspiron 15 (5568/5567) 13 (5368/5378) 7368 42Whr 3Cell Battery",
      price: 24,
      imageUrl: "/images/Dell Inspiration 15.jpg",
    },
    {
      id: 42,
      name: "Captics Universal Travel Adaptor",
      price: 15,
      imageUrl: "/images/Captics Universal Adaptor.jpg",
    },
    {
      id: 43,
      name: "ASUS Vivobook 15",
      price: 568,
      imageUrl: "/images/ASUS Vivobook 15.webp",
    },
    {
      id: 44,
      name: "Honor X9b 5G",
      price: 246,
      imageUrl: "/images/Honor X9b.webp",
    },
    {
      id: 45,
      name: "Spigen Iphone Mobile Case",
      price: 10,
      imageUrl: "/images/Spigen Iphone Mobile case.jpg",
    },
    {
      id: 46,
      name: "Samsung S20 FE 5g",
      price: 250,
      imageUrl: "/images/Samsung S20 FE.jpg",
    },
    {
      id: 47,
      name: "Nikon Z6 II Mirrorless Camera",
      price: 1712,
      imageUrl: "/images/Nikon Camera.jpg",
    },
    {
      id: 48,
      name: "Saregama Carvaan Premium Music Player",
      price: 67,
      imageUrl: "/images/Saregama Carvaan.jpg",
    },
    {
      id: 49,
      name: "JBL PartyBox 710 Bluetooth Party Speaker",
      price: 615,
      imageUrl: "/images/JBL Partybox.jpg",
    },
    {
      id: 50,
      name: "Wings Phantom Pro Earphones Gaming Earbuds",
      price: 10,
      imageUrl: "/images/Wings Phontom.jpg",
    },
    {
      id: 51,
      name: "OnePlus 163.8 cm (65 inches) U Series 4K LED Smart Android TV 65U1S (Black)",
      price: 587,
      imageUrl: "/images/OnePlus TV.jpg",
    },
    {
      id: 52,
      name: "Logitech G923 Racing Wheel and Pedals",
      price: 426,
      imageUrl: "/images/Logitech gaming wheel.jpg",
    },
    {
      id: 53,
      name: "ASUS ROG Strix GA35, 12 Core, AMD Ryzen 9 5900X, Gaming Desktop (32GB/1TB HDD + 1TB SSD/10GB NVIDIA GeForce RTX 3080 Graphics/Windows 11",
      price: 2455,
      imageUrl: "/images/ASUS ROG Gaming Desktop.jpg",
    },
    {
      id: 54,
      name: "Duracell 20000 MAH Power Bank",
      price: 29,
      imageUrl: "/images/Duracell Powerbank.webp",
    },
    {
      id: 55,
      name: "Dell G15-5520 Gaming Laptop",
      price: 620,
      imageUrl: "/images/Dell Gaming Laptop.jpg",
    },
    {
      id: 56,
      name: "YAMAHA PSR-I500 PORTABLE KEYBOARD WITH ADAPTOR",
      price: 187,
      imageUrl: "/images/Yamaha Keyboard.jpg",
    },
    {
      id: 57,
      name: "HP 930 Creator Wireless Mouse",
      price: 24,
      imageUrl: "/images/Hp wireless Mouse.webp",
    },
    {
      id: 58,
      name: "Apple Leather Sleeve Basic Case",
      price: 11,
      imageUrl: "/images/Apple leather sleeve.jpg",
    },
    {
      id: 59,
      name: "Apple Watch Ultra Smart Watch",
      price: 786,
      imageUrl: "/images/Apple Watch ultra.webp",
    },
    {
      id: 60,
      name: "Sony Car Stereo XAV-AX3200 17.6 cm (6.95 inch) Digital Media Receiver with Bluetooth, Android Auto, Apple Car Play, 10 Band Equalizer",
      price: 161,
      imageUrl: "/images/Sony Car Display.jpg",
    },
    // Add more products as needed
  ];

export default products;
